Mobile setup
NgozikaNwocha/Port-folio pull request #2
Opened 2022-07-01 16:38 UTC by NgozikaNwocha

Added the mobile setup for my portfolio project.

2022-07-01 17:14 UTC, wuletawwonte requested changes
# Hi @NgozikaNwocha  👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

- [ ] Please update the README file to include a getting started section, technologies used and a project description section that explains and showcases what your project does. A well-crafted README is a crucial part of your repository. You can use [Microverses readme template](https://github.com/microverseinc/readme-template)
- [ ] Please try to list all the changes you made in this pull request in the pull request description. 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-01 17:14 UTC, wuletawwonte commented on index.html
> +        </div>
- [ ] Please export the whole hamburger icon from the Figma template. That way you can minimize the code in the HTML file and it's simpler to style.

2022-07-01 17:14 UTC, wuletawwonte commented on index.html
> +        <a href="#" class="logo">Ngozika</a>
- [ ] Please move this logo link out of the nav block. only the hamburger menu icon needs to be placed inside the nav tag.

2022-07-01 17:14 UTC, wuletawwonte commented on index.html
> +            Glad to see <br />you!
- [ ] I think it would be better if you use `section` tag here. Because the section tag represents a generic standalone section of the document.

2022-07-01 17:14 UTC, wuletawwonte commented on style.css
> +  background-image: url("images/background-image.svg");
- [ ] There is no images folder in the project. The background image is not loading. Please add the folder and its content to the project.

![Screen Shot 2022-07-01 at 20 09 50](https://user-images.githubusercontent.com/12524453/176939941-9ae8543c-8348-4d63-81d9-3b8e81277ee0.png)

2022-07-01 17:14 UTC, wuletawwonte commented on index.html
> +                <img src="images/Medium.svg" alt="Medium"/>
- [ ] Please add the images folder with its content.

2022-07-02 10:38 UTC, Nemwel-Boniface approved these changes
## Hello @NgozikaNwocha      :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes that were requested by the previous reviewer.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 10:40 UTC, merged